//! Luau definition file (`.d.luau`) emitter for [luau-lsp].
//!
//! Produces a single `.d.luau` source string from a [`crate::DocModel`].
//! The output is suitable for loading via `luau-lsp analyze --defs=...`
//! or as a workspace definition file in editor configurations.
//!
//! [luau-lsp]: https://github.com/JohnnyMorganz/luau-lsp

use std::fmt::Write;

use crate::{DocModel, FunctionDoc, ModuleDoc, ParamDoc, ReturnDoc, TypeRef, UserdataDoc};

/// Render a [`DocModel`] as a single `.d.luau` source string.
pub fn render_luau(model: &DocModel) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by shingetsu-docgen — do not edit by hand.\n");

    for ud in &model.userdata_types {
        render_userdata(ud, &mut out);
    }
    for m in &model.modules {
        render_module(m, &mut out);
    }
    out
}

fn render_userdata(ud: &UserdataDoc, out: &mut String) {
    out.push('\n');
    write_doc_comment(out, ud.doc.as_deref(), "");
    writeln!(out, "declare class {}", ud.name).ok();

    for f in &ud.fields {
        write_doc_comment(out, f.doc.as_deref(), "    ");
        writeln!(out, "    {}: {}", f.name, f.ty.display).ok();
    }
    for m in &ud.methods {
        write_doc_comment(out, m.doc.as_deref(), "    ");
        writeln!(out, "    {}", method_decl(m)).ok();
    }
    // Metamethods are intentionally omitted: luau exposes them via
    // operators (`a + b`, `#x`), not as named methods reachable from
    // user code.  Including `function __add(self, ...)` here would
    // produce something luau-lsp does not understand as a metamethod
    // and which users cannot call directly anyway.
    out.push_str("end\n");
}

fn render_module(m: &ModuleDoc, out: &mut String) {
    out.push('\n');
    write_doc_comment(out, m.doc.as_deref(), "");
    writeln!(out, "declare {}: {{", m.name).ok();

    for f in &m.fields {
        write_doc_comment(out, f.doc.as_deref(), "    ");
        writeln!(out, "    {}: {},", f.name, f.ty.display).ok();
    }
    for fun in &m.functions {
        write_doc_comment(out, fun.doc.as_deref(), "    ");
        writeln!(out, "    {}: {},", fun.name, function_type(fun)).ok();
    }
    out.push_str("}\n");
}

/// `function name(self, args): rettype` form used inside a
/// `declare class` block.  `self` is always present and unannotated
/// per the luau-lsp class declaration grammar.
fn method_decl(m: &FunctionDoc) -> String {
    let params = render_params(&m.params, m.variadic.as_ref(), /* leading_self */ true);
    let ret = render_returns(&m.returns);
    format!("function {}({}): {}", m.name, params, ret)
}

/// `(args) -> rettype` form used inside a `declare X: { ... }` block.
fn function_type(f: &FunctionDoc) -> String {
    let params = render_params(&f.params, f.variadic.as_ref(), false);
    let ret = render_returns(&f.returns);
    format!("({}) -> {}", params, ret)
}

fn render_params(params: &[ParamDoc], variadic: Option<&TypeRef>, leading_self: bool) -> String {
    let mut parts: Vec<String> = Vec::new();
    if leading_self {
        parts.push("self".to_owned());
    }
    for (i, p) in params.iter().enumerate() {
        let name = p.name.clone().unwrap_or_else(|| format!("arg{}", i + 1));
        let ty = if p.optional {
            format!("{}?", p.ty.display)
        } else {
            p.ty.display.clone()
        };
        parts.push(format!("{name}: {ty}"));
    }
    if let Some(v) = variadic {
        parts.push(format!("...: {}", v.display));
    }
    parts.join(", ")
}

fn render_returns(returns: &[ReturnDoc]) -> String {
    match returns.len() {
        0 => "()".to_owned(),
        1 => returns[0].ty.display.clone(),
        _ => format!(
            "({})",
            returns
                .iter()
                .map(|r| r.ty.display.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// Emit `--- ` doc-comment lines for the given doc text, each
/// prefixed with `indent`.  `None` or empty text emits nothing.
fn write_doc_comment(out: &mut String, doc: Option<&str>, indent: &str) {
    let Some(text) = doc else { return };
    if text.is_empty() {
        return;
    }
    for line in text.lines() {
        writeln!(out, "{indent}--- {line}").ok();
    }
}
